######################################################################
# Automatically generated by qmake (3.0) ?? ?? 10 22:13:05 2014
######################################################################

TEMPLATE = app
TARGET = student
INCLUDEPATH += .

# Input
QT += network
CONFIG += console
HEADERS += student.h
SOURCES += main.cpp student.cpp
